---
abstract: 'use OpenLDAPs LMDB Key-Value store as a cache backend.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: '0'
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CHI-Driver-LMDB
provides:
  CHI::Driver::LMDB:
    file: lib/CHI/Driver/LMDB.pm
    version: '0.001000'
  CHI::Driver::LMDB::t::CHIDriverTests:
    file: lib/CHI/Driver/LMDB/t/CHIDriverTests.pm
    version: '0.001000'
requires:
  CHI::Driver: '0'
  CHI::Test: '0'
  CHI::t::Driver: '0'
  Carp: '0'
  File::Spec::Functions: '0'
  LMDB_File: '0'
  Moo: '0'
  Path::Tiny: '0'
  parent: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentfredric/CHI-Driver-LMDB/issues
  homepage: https://github.com/kentfredric/CHI-Driver-LMDB
  repository: https://github.com/kentfredric/CHI-Driver-LMDB.git
version: '0.001000'
x_BuiltWith:
  modules:
    CHI::Driver: '0.58'
    CHI::Test: '0.58'
    CHI::t::Driver: '0.58'
    CPAN::Meta: '2.142060'
    Carp: '1.34'
    Dist::Zilla::Plugin::Author::KENTNL::RecommendFixes: '0.003002'
    Dist::Zilla::Plugin::Authority: '1.006'
    Dist::Zilla::Plugin::AutoPrereqs: '5.020'
    Dist::Zilla::Plugin::BumpVersionAfterRelease: '0.002'
    Dist::Zilla::Plugin::ConfirmRelease: '5.020'
    Dist::Zilla::Plugin::CopyFilesFromBuild: '0.103510'
    Dist::Zilla::Plugin::EOLTests: '0.02'
    Dist::Zilla::Plugin::Git::Check: '2.023'
    Dist::Zilla::Plugin::Git::Commit: '2.023'
    Dist::Zilla::Plugin::Git::CommitBuild: '2.023'
    Dist::Zilla::Plugin::Git::Contributors: '0.007'
    Dist::Zilla::Plugin::Git::GatherDir: '2.023'
    Dist::Zilla::Plugin::Git::NextRelease: '0.003000'
    Dist::Zilla::Plugin::Git::Tag: '2.023'
    Dist::Zilla::Plugin::GithubMeta: '0.46'
    Dist::Zilla::Plugin::License: '5.020'
    Dist::Zilla::Plugin::MakeMaker: '5.020'
    Dist::Zilla::Plugin::Manifest: '5.020'
    Dist::Zilla::Plugin::ManifestSkip: '5.020'
    Dist::Zilla::Plugin::MetaConfig: '5.020'
    Dist::Zilla::Plugin::MetaData::BuiltWith: '1.003000'
    Dist::Zilla::Plugin::MetaJSON: '5.020'
    Dist::Zilla::Plugin::MetaProvides::Package: '2.001002'
    Dist::Zilla::Plugin::MetaTests: '5.020'
    Dist::Zilla::Plugin::MetaYAML: '5.020'
    Dist::Zilla::Plugin::MinimumPerl: '1.003'
    Dist::Zilla::Plugin::PodCoverageTests: '5.020'
    Dist::Zilla::Plugin::PodSyntaxTests: '5.020'
    Dist::Zilla::Plugin::PodWeaver: '4.006'
    Dist::Zilla::Plugin::Prereqs: '5.020'
    Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0.003001'
    Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.142470'
    Dist::Zilla::Plugin::ReadmeFromPod: '0.21'
    Dist::Zilla::Plugin::RewriteVersion::Sanitized: '0.001003'
    Dist::Zilla::Plugin::RunExtraTests: '0.022'
    Dist::Zilla::Plugin::Test::CPAN::Changes: '0.008'
    Dist::Zilla::Plugin::Test::Compile::PerFile: '0.002002'
    Dist::Zilla::Plugin::Test::Kwalitee: '2.11'
    Dist::Zilla::Plugin::Test::MinimumVersion: '2.000005'
    Dist::Zilla::Plugin::Test::Perl::Critic: '2.112410'
    Dist::Zilla::Plugin::Test::ReportPrereqs: '0.019'
    Dist::Zilla::Plugin::TestRelease: '5.020'
    Dist::Zilla::Plugin::Twitter: '0.025'
    Dist::Zilla::Plugin::UploadToCPAN: '5.020'
    Dist::Zilla::PluginBundle::Author::KENTNL: '2.020001'
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: '2.001000'
    ExtUtils::MakeMaker: '6.98'
    File::Spec: '3.49'
    File::Spec::Functions: '3.49'
    LMDB_File: '0.05'
    Moo: '1.006000'
    Path::Tiny: '0.056'
    Pod::Coverage::TrustPod: '0.100003'
    Test::CPAN::Changes: '0.30'
    Test::CPAN::Meta: '0.23'
    Test::Kwalitee: '1.22'
    Test::More: '1.001006'
    Test::Pod: '1.48'
    Test::Pod::Coverage: '1.10'
    parent: '0.228'
    strict: '1.08'
    utf8: '1.14'
    warnings: '1.26'
  perl:
    original: v5.21.3
    qv: 1
    version:
      - 5
      - 21
      - 3
  perl-config:
    gccversion: 4.8.3
    git_commit_id: 640eedb9ffcac7a9c2793689044e84bfd9af3045
    git_describe: v5.21.2-215-g640eedb
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.16.1-aufs x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: '5.021003'
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.020'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '2.001002'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '1.003000'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '0'
          order_by: name
          paths: []
      name: '@Author::KENTNL/Git::Contributors'
      version: '0.007'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::KENTNL/CopyXBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.11'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/CHI/Driver/LMDB.pm
            - lib/CHI/Driver/LMDB/t/CHIDriverTests.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.002002'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::RewriteVersion::Sanitized
      config:
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: '6'
          normal_form: numify
      name: '@Author::KENTNL/RewriteVersion::Sanitized'
      version: '0.001003'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/BundleDevelRequires'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/MakeMaker'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::RecommendFixes
      name: '@Author::KENTNL/Author::KENTNL::RecommendFixes'
      version: '0.003002'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::Check'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_dirty_files'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: '0'
          tag: 0.001000-source
          tag_format: '%v-source'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_master'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.003000'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      name: '@Author::KENTNL/BumpVersionAfterRelease'
      version: '0.002'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match:
            - (?^:^lib/)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_release_changes'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: '0'
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          signed: '0'
          tag: '0.001000'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_release'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'build.requires = build.recommends'
            - 'test.requires = test.recommends'
            - 'runtime.requires = runtime.recommends'
            - 'configure.requires = configure.recommends'
            - 'develop.requires = develop.recommends'
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          modules:
            - ExtUtils::MakeMaker
            - Test::More
          source_relation: requires
          target_relation: recommends
      name: '@Author::KENTNL/Prereqs::Recommend::MatchInstalled'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'develop.requires = develop.requires'
          applyto_phase:
            - develop
          modules:
            - Dist::Zilla::PluginBundle::Author::KENTNL
          source_relation: requires
          target_relation: recommends
      name: '@Author::KENTNL/always_latest_develop_bundle'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.020'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.020'
x_authority: cpan:KENTNL
